export const AUTHACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  CREDITWALLET: 'CREDITWALLET'
};

export const USERACTIONS = {
  ASSIGN: 'ASSIGN',
  PICKUP: 'PICKUP',
  DELIVER: 'DELIVER'
};

export const UICONSTANTS = {
  TOGGLECLIENT: 'TOGGLECLIENT'
};
