export const AUTHACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN: 'LOGIN',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  INIT_SINGUP: 'INIT_SINGUP',
  CREDITWALLET: 'CREDITWALLET',
  DEBITWALLET: 'DEBITWALLET'
};

export const USERACTIONS = {
  SET_USERJOBBIDS: 'SET_BIDS',
  SET_LOADING: 'SET_LOADING',
  ASSIGN: 'ASSIGN',
  PICKUP: 'PICKUP',
  DELIVER: 'DELIVER',
  SET_ALERT: 'SET_ALERT'
};

export const UICONSTANTS = {
  TOGGLECLIENT: 'TOGGLECLIENT'
};
